PROMPT DROP TABLES;

DROP TABLE Book CASCADE CONSTRAINT;
DROP TABLE Student CASCADE CONSTRAINT;
DROP TABLE Orders CASCADE CONSTRAINT;
DROP TABLE Orders_Book CASCADE CONSTRAINT;
DROP TABLE Orders_Total CASCADE CONSTRAINT;


COMMIT;